falcosecurity/driverkit

cmd/config_options.go, cmd/docker.go, cmd/kubernetes.go, cmd/root.go, cmd/root_options.go, cmd/walk.go, go.mod, pkg/modulebuilder/docker.go, pkg/modulebuilder/kubernetes.go, pkg/modulebuilder/templates.go
/kind feature
/area cmd
/area pkg
Fixes #
```release-note
new: timeout flag
fix: docker copy outputs just the module
new: timeout for kubernetes build processor
```
=> Copy from docker buildprocessor just works™

README.md, pkg/modulebuilder/builder/ubuntu.go, pkg/modulebuilder/builder/vanilla.go
/area docs
Fixes #
```release-note
NONE
```
=> docs: update documentation for supported distributions

README.md, cmd/root_options.go, pkg/kernelrelease/kernelrelease_test.go, pkg/modulebuilder/builder/builders.go, pkg/modulebuilder/builder/debian.go, pkg/modulebuilder/builder/ubuntu.go
/kind feature
/area build
/area cmd
/area pkg
/area docs
/area tests
We need to build for debian kernels, this PR adds support to them.
Fixes #13 
```release-note
new: debian target support
```
=> Debian builder

README.md
Signed-off-by: Vicente Herrera <vicenteherrera@vicenteherrera.com>
> /kind bug
> /kind design
> /area build
> /area cmd
> /area pkg
/area docs
> /area tests
Documentation mentions use of parameter -o, that do not exist. The correct one is --output-module, that doesn't have a shorthand.
Fixes #
Tested executing successfully:
`driverkit kubernetes --output-module falco.ko --kernelversion=81 --kernelrelease=4.15.0-72-generic …
=> Changed non-existant parameter -o to --output-module in documentation

.circleci/config.yml
/kind bug
/area build
Fixes #
```release-note
NONE
```
=> fix: docker image dependencies

.circleci/config.yml, Makefile
/kind bug
/area build
Fixes deps for push docker images.
```release-note
NONE
```
=> fix: ci image dependencies

.circleci/config.yml
/kind bug
/area build
Fixes the GIT_BRANCH variable
```release-note
NONE
```
=> fix: image branch name

Makefile
/kind bug
/area build
```release-note
NONE
```
=> fix: disable test packages filter

build/driverkit.Dockerfile
/kind cleanup
/kind feature
/area build
Removeds unneeded deps from driverkit image.
```release-note
NONE
```
=> fix: remove unneded dependencies

pkg/driverbuilder/builder/centos.go
/kind feature
/area pkg
Adds new stream releases paths to look for (centos target).
NONE
```release-note
update: 8.1.1911 stream releases (centos target)
```
=> update(pkg/driverbuilder): add new stream releases to look for

Makefile, README.md, build/driverkit.Dockerfile, go.mod, go.sum, pkg/driverbuilder/builder/amazonlinux.go, pkg/driverbuilder/builder/amazonlinux2.go, pkg/driverbuilder/builder/target.go, pkg/kernelrelease/kernelrelease.go, pkg/kernelrelease/kernelrelease_test.go
/kind feature
/area pkg
/area tests
Fixes #41 
Fixes #45 
This is needed to avoid situations like https://github.com/falcosecurity/falco/issues/1113
```release-note
new: amazonlinux2 target
new: amazonlinux target
```
=> amazonlinux2 and amazonlinux targets

.gitignore, pkg/driverbuilder/docker.go
/kind bug
/area cmd
/area pkg
Fixes #
```release-note
fix(builder/docker): pull builder if not found locally
```
=> fix: pull builder if not found locally

pkg/driverbuilder/docker.go
Co-authored-by: Lorenzo Fontana <lo@linux.com>
/kind bug
/area pkg
Fixes #
```release-note
fix(builder/docker): image pull wait for completion
```
=> fix(pkg/driverbuilder): wait the pull to download

pkg/driverbuilder/docker.go
/kind bug
/area pkg
Fixes #
```release-note
NONE
```
=> fix(builder/docker): race conditions in the docker builder

pkg/driverbuilder/builder/ubuntu.go
/kind feature
/area pkg
Fixes #
```release-note
NONE
```
=> Ubuntu target improvements

README.md
/area docs
Fixes #
```release-note
NONE
```
=> docs: guide to add a new builder

.circleci/config.yml, RELEASE.md
/kind bug
/area build
/area docs
The current release process needs to be documented.
The current release process based upon CircleCI needs to be fixed.
```release-note
docs: release instructions
```
=> fix release + release docs

RELEASE.md
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
/area docs
The git implementation of CircleCI (used [here](https://github.com/falcosecurity/driverkit/blob/master/.circleci/config.yml#L15)) does not work well with annotated tags (here an [example of the problem](https://app.circleci.com/pipelines/github/falcosecurity/driverkit/102/workflows/6653c7b9-91f9-4581-bb60-6a36e3965fb9/jobs/144)).
Fixes #
```release-note
NONE
```
=> docs(RELEASE.md): do not use an annotated tag

pkg/driverbuilder/builder/debian.go
/kind bug
/area pkg
This PR splits the way the Debian builder looks for Linux kernel headers and their dependencies (ie., Linux kernel headers common package).
Previously, this builder was looking for both the packages with one regex. This operation was resulting in selecting only the Linux headers package and not the common one (which is needed).
Fixes #81
These changes do not break the building of Falco drivers for Linux kernels 3.16, 4.19 (tested manually).
```release-note
fix(debian): …
```
=> fix the building of Falco drivers for kernels 5.10.x (on debian)

Makefile, pkg/driverbuilder/builder/amazonlinux.go
/kind feature
/area build
/area pkg
Fixes #90
This PR:
* fixes a bug in the `Makefile` (now it ensures to use a specific shell)
* adds support for Amazon Linux 2 extra kernels
```release-note
NONE
```
=> Add support for Amazon Linux 2 extra kernels 

build/builder.Dockerfile
/kind cleanup
/area build
Fixes #89 
```release-note
NONE
```
=> update(build): fetch deps from download.falco.org

RELEASE.md
/kind cleanup
/area docs
Fixes wrong slack URL.
NONE
```release-note
NONE
```
=> docs: fix slack URL inside the RELEASE file

README.md, cmd/root.go, cmd/root_options.go, cmd/testdata/autohelp.txt, cmd/testdata/dockernoopts.txt, cmd/testdata/help-flag.txt, cmd/testdata/help.txt, cmd/testdata/invalid-proxyconfig.txt, cmd/testdata/non-existent-processor.txt, pkg/driverbuilder/builder/amazonlinux.go, pkg/driverbuilder/builder/build.go, pkg/driverbuilder/builder/builders.go, pkg/driverbuilder/builder/centos.go, pkg/driverbuilder/builder/debian.go, pkg/driverbuilder/builder/ubuntu.go, pkg/driverbuilder/builder/vanilla.go, pkg/driverbuilder/docker.go, pkg/driverbuilder/kubernetes.go, pkg/driverbuilder/templates.go
> /kind bug
> /kind design
/kind feature
/area build
/area cmd
/area pkg
> /area docs
> /area tests
The falco libs client might require a kernel module name which is not called `falco` / `falco`, depending on the client. Allow these two options to be passed as command line flags via `--moduledrivername` and `--moduledevicename`
Fixes #
```release-note
new(driverkit): add --moduledrivername and …
```
=> new(driverkit): allow configuring the module driver and device name

.circleci/config.yml
/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
NONE
```
=> fix(build): fixed circleci config: cimg/base uses ubuntu and not alpine.

Makefile
/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
NONE
```
=> update(build): use custom buildx builder with docker-container driver.

.circleci/config.yml, Makefile
/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
NONE
```
=> fix(ci): fixed docker buildx usage.

.goreleaser.yml, Makefile
/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Basically, we've been hit by the same bug as https://github.com/falcosecurity/event-generator/pull/66.
Fixes #
```release-note
NONE
```
=> fix(build): fix arm64 support on alpine (that is used by official docker image)

Makefile
> /kind bug
/kind cleanup
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
mattn/go-sqlite supported the `sqlite_omit_load_extension` key (https://github.com/mattn/go-sqlite3#feature--extension-list); new driver does not.
Tested the build and seems to make no difference.
Moreover, tested an amazonlinux2 build; again, no difference.
**Does this PR introduce a …
=> chore(build): dropped sqlite_tags and consequently empty GOTAGS.

pkg/driverbuilder/builder/builders.go
> /kind bug
> /kind design
/kind feature
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Added support for relative urls in getResolvingURLs function (needed as kernel-crawler does not resolve relative urls, eg: for amazonlinux2; see: https://github.com/falcosecurity/kernel-crawler/blob/main/kernels/aarch64/list.json#L9.
Fixes # …
=> new(pkg/builder): allow `kernelurls` relative urls.

pkg/driverbuilder/builder/ubuntu.go
/kind bug
> /kind design
> /area build
> /area cmd
> /area pkg
> /area docs
> /area tests
#171 got approved lightning quick (before CI had finished), and integration_tests is failing. This fixes it.
Fixes #
```release-note
```
=> Fix CI failure

go.mod, go.sum, pkg/driverbuilder/docker.go
/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Possibly fixed download of files from builder container (ie: kmod and probe).  
Now we are using exactly same code as `docker cp` command: https://github.com/docker/cli/blob/87add19e2f585af3d6e70df124a67b8f603ca50e/cli/command/container/cp.go#L156
Moreover, run `go mod tidy`.
Hopefully the 
```
ERRO error expanding tar                           error="gzip: invalid header"
DEBU context …
```
=> fix(pkg): hopefully fix invalid gzip header error when downloading files from builder container

.goreleaser.yml
> /kind bug
/kind cleanup
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
NONE
```
=> fix(goreleaser): drop GOTAGS support, after #162.

.circleci/config.yml
> /kind bug
> /kind design
/kind feature
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
The PR uses circleCI `store_artifacts` to store each build's artifacts for 30days on circleCI (the default value).
This can be useful to quickly test a ci build.
Fixes #
```release-note
NONE
```
=> chore(ci): store_artifacts on circleci for each build

cmd/testdata/completion-targets.txt, pkg/driverbuilder/builder/archlinux.go, pkg/driverbuilder/builder/templates/archlinux.sh
/kind feature
/area pkg
It can be useful to quickly test newest kernel releases.
Fixes #
```release-note
new(builder): added an archlinux builder.
```
=> new(builder): added an archlinux builder.

OWNERS
/area docs
As privately discussed with @dwindsor, i am opening this PR to propose myself as a driverkit maintainer.
In the latest 2-3 months, i have been as active as possible, bringing to driverkit:
* arm64 support
* improved CI with integration tests
* lots of bug fixes
* lots of small and not-so-small refactorings 
* just (but imo this is the best part :D) ideas to play around
I am going to publicly propose myself during the next community call, then leave this open for a public discussion, for a week or so.
Fixes # …
=> update(docs): add me to owners.

cmd/testdata/completion-targets.txt, pkg/driverbuilder/builder/minikube.go
```
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
```
> /kind bug
> /kind design
/kind feature
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
This PR introduces a new builder for minikube, which uses the vanilla builder under the hood when building the drivers for the minikube distro.
Fixes #
```release-note
feature(pkg/driverbuilder): add minikube target
```
=> feature(pkg/driverbuilder): add minikube target

README.md
```
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
```
> /kind bug
> /kind design
> /area build
> /area cmd
> /area pkg
/area docs
> /area tests
Add minikube example configuration file in `README.md` file.
Fixes #
```release-note
update(docs): add minikube example configuration file
```
=> update(docs): add minikube example configuration file

pkg/driverbuilder/templates.go
/kind bug
/area pkg
Fix lockfile name.
None
=> feat(kebernetes-incluster): fix lock file name

.circleci/config.yml, Makefile
/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
```
=> chore(ci): Re-enable integration_test target

Example_configs.md, pkg/driverbuilder/builder/archlinux.go
/kind feature
/area build
Archlinux [officially](https://wiki.archlinux.org/title/Kernel#Officially_supported_kernels) support 4 kernel flavours: main, lts, hardened and zen 
Fixes #
```release-note
NONE
```
=> feat: support all the archlinux kernel flavours

docs/builder_images.md, pkg/driverbuilder/builder/ubuntu.go, pkg/driverbuilder/builder/ubuntu_test.go
/kind bug
/area pkg
/area docs
```release-note
fix: find right version of gcc for ubuntu
```
=> fix: find right version of gcc for ubuntu

pkg/driverbuilder/builder/minikube.go
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
This PR implements the `GCCVersionRequestor` interface for the minikube builder in order to use the correct gcc version while building drivers for `minikube`. The minikube builder still shares some code with the `vanilla` builder but reimplements some specific methods.
Fixes #
**Does this PR introduce a …
=> update(builder/minikube): implement the GCCVersionRequestor interface for the minikube builder

README.md
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore(readme): add 2 beautiful badges

pkg/driverbuilder/builder/almalinux.go, pkg/driverbuilder/builder/rocky.go, pkg/driverbuilder/builder/templates/almalinux.sh
/kind feature
/area build
/area cmd
Introduced AlmaLinux to drivekit and updated Rocky for support version 9
=> Added AlmaLinux drivekit and RockyLinux 9

pkg/driverbuilder/builder/opensuse.go, pkg/driverbuilder/builder/templates/opensuse.sh
Signed-off-by: Logan Bond <lbond@secureworks.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Adds initial support for OpenSUSE 🙂 
Fixes # N/A
I have a companion PR on kernel-crawler open to add support there too. Kernel-crawler's output helped build the URLs for this PR: https://github.com/falcosecurity/kernel-crawler/pull/59
Adds initial …
=> Add initial openSUSE support

pkg/driverbuilder/builder/debian.go, pkg/driverbuilder/builder/templates/debian.sh
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
/kind feature
/area pkg
Proxmox kernel are based on Debian, but has customs headers name. This litlle change make possible the compilation of the driver of a proxmox kernel.
None
```release-note
"NONE" 
```
=> feat(debian-pve-build): compile proxmox kernel's driver

pkg/driverbuilder/builder/bottlerocket.go
/kind feature
/area pkg
Adds support for bottlerocket, using same mechanism as minikube; see kernel-crawler PR: https://github.com/falcosecurity/kernel-crawler/pull/79
Fixes #
```release-note
new: add support for bottlerocket
```
=> new(builder): add bottlerocket os support.

Makefile
/kind bug
/area build
Builder images are now platform dependent images (ie: we push them under different names for each arch), because architecture is part of the new builder image name protocol.
Therefore, we don't need to use any `docker manifest` for them.
Fixes #
```release-note
NONE
```
=> fix(makefile): fixed images push: we don't need `docker manifest` anymore for builder images

Example_configs.md, docker/builders/builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0.Dockerfile, docs/driverkit.md, docs/driverkit_docker.md, docs/driverkit_images.md, docs/driverkit_kubernetes-in-cluster.md, docs/driverkit_kubernetes.md, pkg/driverbuilder/builder/oracle.go, pkg/driverbuilder/builder/templates/oracle.sh
> /kind bug
> /kind design
/kind feature
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Adding in Oracle support 🙂
Kernel Crawler supports it, but I realized Driverkit doesn't. I don't think it will be too hard to add.
Fixes # N/A
Adds `--target oracle`
```release-note
Initial Oracle Support!
```
=> Adding Initial Oracle Support

pkg/driverbuilder/builder/aliyunlinux.go, pkg/driverbuilder/builder/templates/aliyunlinux.sh
/kind feature
/area build
Drivekit builder for Alibaba Cloud Linux
=> Alibaba Cloud Linux(AliyunLinux) 2 and 3 drivekit

OWNERS
/area docs
As proposed in #256, I'm quite exited to propose myself as `Driverkit` Maintainers, mainly to continue to support and improve the Kubernetes part in addition of improving automated usability, reviews MR and more if needed.
Whatever the result is, I really appreciate the proposal, it's always a pleasure to get our work recognize!
=> vote: Applying for Maintainer

docs/driverkit.md, docs/driverkit_docker.md, docs/driverkit_images.md, docs/driverkit_kubernetes-in-cluster.md, docs/driverkit_kubernetes.md, pkg/driverbuilder/builder/amazonlinux.go
/kind feature
/area pkg
Fixes #
```release-note
new: added al2023 support
```
=> new(pkg,docs): added al2023 support.

docs/driverkit.md, docs/driverkit_docker.md, docs/driverkit_images.md, docs/driverkit_kubernetes-in-cluster.md, docs/driverkit_kubernetes.md, pkg/driverbuilder/builder/talos.go
/kind feature
/area pkg
The PR  adds a [talos](https://github.com/siderolabs/talos) builder .
Fixes #
WIP because i first want to test that the kernelconfigdata we are fetching can correctly build a working driver.
```release-note
new(pkg): added a talos builder
```
=> new(pkg): add support for talos builder

.circleci/config.yml, pkg/driverbuilder/builder/image.go, pkg/driverbuilder/builder/image_test.go
/kind bug
/kind cleanup
/area build
/area pkg
Plus, fixed an issue with ListImage from docker.
Fixes #
```release-note
NONE
```
=> fix(pkg,ci): enabled back integration tests.

Example_configs.md
What type of PR is this?
Any specific area of the project related to this PR?
/area docs
What this PR does / why we need it:
Fixed typos and improves explanation
Which issue(s) this PR fixes:
Fixes typos and makes the documentation a little clearer
Does this PR introduce a user-facing change?:
No
```
Fixed documentation typos and improves explanation for RHEL9 builder images
```
=> fixed typos and improved RHEL9 builder image explanation

cmd/root_options.go, pkg/driverbuilder/builder/image.go, pkg/driverbuilder/builder/image_test.go, pkg/driverbuilder/builder/ubuntu_test.go
/kind cleanup
/area pkg
Fixes #
```release-note
NONE
```
=> cleanup(pkg,cmd): small images listers refactor.

docker/builders/builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0.Dockerfile, pkg/driverbuilder/builder/photon.go
/kind feature
/area pkg
Moreover, support aarch64 kernelurls for it.
Fixes #
```release-note
new(pkg/driverbuilder): support photonOS 5.0.
```
=> new(pkg/driverbuilder): support photonOS 5.0.

pkg/driverbuilder/builder/templates/photonos.sh
/kind bug
/area pkg
Properly match any kernel flavor.
Fixes #
```release-note
fix(pkg/driverbuilder): fixed PhotonOS builder template regex.
```
=> fix(pkg/driverbuilder): fixed PhotonOS builder template regex.

pkg/driverbuilder/docker.go
/kind bug
/area pkg
The fixed multiplexed docker output merged in #305 had some bugs when the `Read` for the output was truncated, since the case was not managed. 
This is breaking libs CI since the driverkit v0.16.0 tag: https://github.com/falcosecurity/libs/actions/workflows/latest-kernel.yml
Fixes #
```release-note
NONE
```
=> fix(pkg): fixed docker multiplexed output function.

pkg/driverbuilder/builder/debian.go
/kind bug
/area pkg
Fixes #
```release-note
NONE
```
=> fix(pkg/driverbuilder): fixed debian rpi drivers build.

pkg/driverbuilder/builder/builders.go, pkg/driverbuilder/builder/ubuntu.go
/kind bug
/area pkg
This PR fixes the build of multiple drivers:
* ubuntu 6.5 drivers
* ubuntu-lts drivers
Fixes #
```release-note
fix(pkg/driverbuilder): fixed support for ubuntu 6.5 and ubuntu-lts drivers
```
=> fix(pkg/driverbuilder): fixed support for ubuntu-lts.

OWNERS
/kind cleanup
/area docs
As per title. Groups should now be automatically updated via test-infra automation.
Fixes #
```release-note
NONE
```
=> update(owners): trigger group update automation

OWNERS
/kind cleanup
> /area build
> /area cmd
> /area pkg
/area docs
> /area tests
As per previous PR
Fixes #
```release-note
```
=> update(owners): trigger automation

OWNERS
/kind cleanup
/area docs
As per title
Fixes #
```release-note
```
=> chore(OWNERS): trigger automation

go.mod, go.sum, pkg/driverbuilder/docker.go
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
This bump is needed by: fhttps://github.com/falcosecurity/falcoctl/pull/605
Fixes #
```release-note
NONE
```
=> chore(docker): bump docker packaget to v27.0.3+incompatible

.github/workflows/release.yml, .goreleaser.yml
> /kind bug
> /kind design
> /area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
```
=> update(gorelease): bump to v2.0

docs/builder.md, pkg/driverbuilder/builder/archlinux.go
/kind cleanup
/area pkg
/area docs
See https://github.com/falcosecurity/kernel-crawler/pull/196.
Also, updated builders documentation after recent changes.
Fixes #
```release-note
```
=> chore(pkg,docs): use a working mirror for archlinux arm64.

pkg/driverbuilder/builder/fedora.go, pkg/driverbuilder/local.go
/kind bug
/area pkg
Add repository for older kernel updates (see #351).
I also added a warning log to make it easier to debug future similar problems.
Fixes #351
```release-note
NONE
```
=> Add Fedora updates-archive repository for kernel headers download

pkg/driverbuilder/builder/amazonlinux.go
/kind bug
/area pkg
Fixes support for amazonlinux2023; also, removes memleak (`defer` used within a loop).
Fixes #
```release-note
fix(pkg/driverbuilder): fix amazonlinux2023 support.
```
=> fix(pkg/driverbuilder): fix amazonlinux2023 support.

.github/workflows/reusable_build_push_images.yml, .github/workflows/reusable_build_test_driverkit.yml
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore(ci): switch to use cncf provided runners for arm64.

.github/PULL_REQUEST_TEMPLATE.md, RELEASE.md
Fixes #
```release-note
NONE
```
=> fix(docs): fixed release document.

.github/workflows/reusable_build_push_images.yml, .github/workflows/reusable_build_test_driverkit.yml
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore(ci): switch to github provided arm64 runners.

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/reusable_build_test_driverkit.yml
/kind cleanup
/area build
As per title
Fixes #
```release-note
NONE
```
=> cleanup(ci): use gh action hashes
