pkg/driverbuilder/docker.go

/kind feature
/area pkg
Pull the driverkit-builder docker image (docker processor).
NONE
```release-note
update: pull the driverkit-builder docker image while building with docker processor
```

fix: pull image in docker builder

---

cmd/root.go
cmd/root_options.go
go.mod
go.sum
pkg/driverbuilder/docker.go
validate/semver.go
validate/validate.go

/kind bug
/kind feature
/area cmd
/area pkg
This PR makes the image pull honor the common docker behavior for image pulls.
Also, this PR introduces the ability to specify semver-ish tags as `driverversion` options.
Fixes #33 
Fixes #34
```release-note
fix: honor docker image pull behaviour
update: accept semver-ish strings as driver version option values
```

options validation improvements + fix for docker image pull

---

cmd/config_options.go
cmd/root.go
cmd/root_options.go

/kind bug
> /kind design
> /area build
/area cmd
> /area pkg
> /area docs
> /area tests
This PR corrects the logic of how `RootOptions` are fetched and merged. 
Now, each item takes precedence over the item below it:
- flag
- env
- config
- default 
Also:
- fields present in `ConfigOptions` are skipped, and can only be set using command line flags
- nested flags from config file are supported too
- not-nested flags containing `-` in their name work too
This PR also …

fix(cmd): correct options precedence and support for flags containing dashes

---

pkg/driverbuilder/builder/ubuntu.go

/kind bug
/area pkg
It adds "security.ubuntu.com/ubuntu/pool/main/l" base URLs for ubuntu-generic and ubunut-aws targets.
Moreover, it changes the GCC version in use depending on the kernel version for which the Falco module is being built.
NONE
```release-note
update(pkg/driverbuilder/builder/ubuntu): security.ubuntu.com/ubuntu/pool/main/l as base url for ubuntu-aws and ubuntu-generic targets
fix(pkg/driverbuilder/builder/ubuntu): some 3.x kernels needs an older GCC 
```

Refinements to ubuntu targets

---

pkg/driverbuilder/builder/ubuntu.go

Co-Authored-by: Lorenzo Fontana <lo@linux.com>
/kind bug
/area pkg
Correct regex to find all the `ubuntu-aws-*.*-...` kernel headers in nested folders
Refs https://github.com/falcosecurity/test-infra/pull/172
```release-note
fix: discovery of kernel headers for ubuntu-aws-*.* works correctly now
```

Fix discovery of kernel headers for ubuntu-aws-*.*

---

pkg/driverbuilder/builder/debian.go

Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
/kind feature
/area pkg
@danpopSD reported that they wanted to try Falco on a  `4.19.0-10-cloud-amd64` kernel.
This PR makes sure that driverkit does not ignore the `cloud` extraversion and thus can build for said kernel group.
Fixes #
```release-note
new: build support for debian cloud-amd64 kernels
```

update(pkg/driverbuilder): debian support for cloud-amd64 extraversion

---

RELEASE.md

Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
/area docs
I was doing a release nad noticed that the `RELEASE.md` docs didn't mention the `v` in the versioning scheme which is actually required for the CI to work and also used in the previous releases.
Fixes #
```release-note
NONE
```

docs: release md specify that v is needed in the versioning scheme of the tag

---

pkg/driverbuilder/builder/ubuntu.go
pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

/kind bug
/kind feature
/area pkg
Add supports for GKE kernels to the already existing ubuntu-generic builder.
Fixes #67
Fixes #60
To help the reviewer I provide a YAML configuration file:
```yaml
kernelversion: 46
kernelrelease: 4.15.0-1044-gke
target: ubuntu-generic
output:
module: output/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_ubuntu-generic_4.15.0-1044-gke_46.ko
probe: output/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_ubuntu-generic_4.15.0-1044-gke_46.o
```
```release-note
new: support for GKE kernels in the ubuntu-generic builder …
```

new: support for GKE kernels in the ubuntu-generic builder

---

pkg/driverbuilder/builder/ubuntu.go

/kind feature
/area pkg
This PR adds to the `ubuntu-generic` builder the ability to find GKE 5.4 kernels too.
The URLs are very similar to the GKE 4.15 kernels except for a part in the end that contains the `~18.04.1` string. For this reason, since this string can change in the future, I preferred to explicitly list this other URL structure rather than using regexp or something like that.
NONE
To test it use a YAML like this:
```yaml
kernelversion: 37
kernelrelease: 5.4.0-1035-gke
target: ubuntu-generic
output:
module: …
```

Support also GKE 5.4 kernels (ubuntu-generic builder)

---

Makefile
pkg/driverbuilder/docker.go
pkg/driverbuilder/kubernetes.go

/kind bug
/kind cleanup
/area build
/area pkg
This PR:
* Reverts 7571d8ca6dade13def43a7b69ab3d72f5394719d as it's breaking CI pipelines
* Fixes #91 
I also verified that commit hashes used as driver versions [here](https://github.com/falcosecurity/test-infra/tree/master/driverkit/config) are still consistent and exist also in [falcosecurity/libs](https://github.com/falcosecurity/libs).
```release-note
NONE
```

Revert Makefile shell usage + use `falcosecurity/libs` instead of `draios/sysdig`

---

pkg/driverbuilder/templates.go

When we build the BPF probe, we put ourselves in the kernel context
as if we were a kernel module with the `M=` option.
Doing so requires KBUILD_MODNAME to be defined in newer kernels.
This was already added by @nathan-b in libs here https://github.com/falcosecurity/libs/blob/master/driver/driver_config.h.in
/kind bug
Our [test-infra logs are](https://falco-prow-logs.s3.eu-west-1.amazonaws.com/logs/build-drivers-ubuntu-generic-periodic/1373107107963867136/build-log.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAUIOA5MU2BCUB3HES%2F20210325%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20210325T112632Z&X-Amz-Expire …

fix(pkg/driverbuilder): include KBUILD_MODNAME in driver_config.h for BPF targets

---

README.md

/area docs
This PR updates the `README.md` according to the `builder`-expected default eBPF probe filepath.
The `README.md` currently indicates a wrong expected path for the built probe (`/tmp/driver/probe.ko` instead of `/tmp/driver/probe.o`).
```release-note
NONE
```

docs(readme.md): update ebpf probe default path

---

pkg/driverbuilder/builder/centos.go

/kind bug
/area build
Some CentOS releases have been moved from Stream to Vault since the centos driverbuilder was created. This causes test-infra tests to fail when building CentOS 8.3, 8.2, and 8.1 kernels (8.4 kernels build successfully in test-infra):
```
utils/checkfiles config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-240.10.1.el8_3.x86_64_1.yaml
[36mINFO[0m using config file                             [36mfile[0m=config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-240.10.1.el8_3.x86_64_1.ya …
```

Add CentOS 8 Vault RPMs to centos driverbuilder

---

pkg/driverbuilder/builder/centos.go

CentOS 8.5 was released on 2021-11-16. Since then, CentOS 8.4 has been reclassified as a Vault release; its RPMs are no longer hosted on mirrors.edge.kernel.org.
Fix pkg/driverbuilder/builder/centos.go so it looks for CentOS 8.4 RPMs on vault.centos.org rather than mirrors.edge.kernel.org (which now hosts CentOS 8.5 RPMs).
/kind bug
/area build
Fixes #114 
```release-note
```

driverkit: Move CentOS 8.4 to Vault

---

pkg/driverbuilder/builder/centos.go

/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
In order to support CentOS with kernel 3.10.0-1127 we need support for CentOS Linux release 7.8.2003 (Core). This PR adds it. This will make files like test-infra's `centos_3.10.0-1127.el7.x86_64_1.yaml` build successfully.
Fixes #
```release-note
fix(build): add support for CentOS Linux release …
```

fix(build): add centos version 7.8.2003

---

pkg/driverbuilder/builder/centos.go

> /kind bug
> /kind design
/kind feature
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
This simply adds the necessary versions for CentOS 7.9 and 8.5 as found in the official repos.
Fixes #
Do we already need to add this or do we need to do that only if they're not the latest releases?
```release-note
new(build): add support for CentOS 7.9 and 8.5
```

new(build): add CentOS 7.9 and 8.5

---

build/builder.Dockerfile
pkg/driverbuilder/builder/debian.go

/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Since Falco's eBPF probe supports clang 12 we can use it in the builder image. It appears that debian kernel 5.10 won't compile properly with clang 7, but works fine with 11+. See issue #106 for additional information.
PS: this PR contains the `buster` change from #110 , if this is accepted the other is superseded.
https://github.com/falcosecurity/driverkit/issues/106
Fixes #
**Special …

fix(build): use llvm/clang 12 to build the probe on Linux Kernel 5.x on Debian

---

README.md
cmd/root_options.go
cmd/testdata/autohelp.txt
cmd/testdata/configs/1.yaml
cmd/testdata/docker-from-config-debug.txt
cmd/testdata/docker-override-from-config-debug.txt
cmd/testdata/docker-with-flags-debug.txt
cmd/testdata/dockernoopts.txt
cmd/testdata/help-flag.txt
cmd/testdata/help.txt
cmd/testdata/invalid-proxyconfig.txt
cmd/testdata/non-existent-processor.txt
docs/driverkit.md
docs/driverkit_docker.md
docs/driverkit_kubernetes.md
validate/validate.go

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
/kind cleanup
> /kind design
> /area build
/area cmd
> /area pkg
> /area docs
> /area tests
The default branch of https://github.com/falcosecurity/libs switched from `dev` to `master` a lot of time ago. This PR updates the default value for `--driverversion` accordingly. 
Fixes #
Although having a wrong default value is not strictly a bug, it can cause a bad user experience.
**Does this …

update(cmd): default value for `--driverversion` is now `master`

---

pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

This PR introduces JSON tags for the `KernelRelease` struct, with snake case naming convention.
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
/kind feature
/area pkg
/area tests
If we'd need to encode `KernelRelease`s the transformed data will follow the snake case naming convention.
None
This PR introduces a test for the struct encoding transformation.
```release-note
feat(pkg/kernelrelease): introduce json tags for kernelrelease
action required: KernelRelease JSON-encoded data fields are renamed following snake case
```

feat(pkg/kernelrelease): introduce json tags for kernelrelease

---

pkg/driverbuilder/builder/amazonlinux.go
pkg/driverbuilder/builder/centos.go
pkg/driverbuilder/builder/debian.go
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/vanilla.go
pkg/driverbuilder/docker.go
pkg/driverbuilder/kubernetes.go
pkg/driverbuilder/templates.go

Signed-off-by: Luca Guerra <luca@guerra.sh>
/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
This PR adds support for scap/falco driver versioning, introduced in https://github.com/falcosecurity/libs/pull/39 . Currently, driverkit is broken on any version equal or newer than the above.
Since Driverkit does not use CMake to generate the driver header file, we need to do it at runtime by following the same process that the cmake …

fix(build): support PPM_API_CURRENT_VERSION macros

---

cmd/testdata/completion-targets.txt
pkg/driverbuilder/builder/rocky.go

```bash
./_output/bin/driverkit -l debug docker --output-module \ /tmp/falco_rocky.ko --kernelversion=1
--kernelrelease=4.18.0-348.el8.0.2.x86_64 --driverversion=b7eb0dd65226a8dc254d228c8d950d07bf3521d2
--moduledrivername="falco_rocky" --moduledevicename="falco-rocky" --target=rocky
DEBU Ifilename:       /tmp/driver/module.ko 
DEBU schema_version: 1.0.0                        
DEBU api_version:    1.0.0                        
DEBU build_commit:   b7eb0dd65226a8dc254d228c8d950d07bf3521d2 
DEBU version:        b7eb0dd65226a8dc254d228c8d950d07bf3521d2 
DEBU author:         the Falco authors            
DEBU license:        GPL                          
DEBU rhelversion:    8.5                          
DEBU srcversion: …
```

Add driverbuilder for Rocky Linux

---

pkg/driverbuilder/templates.go

/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
The PR reintroduces PROBE_VERSION define to allow building on old libs versions.
Bug was introduced by: 067a562f25722cdd4bd8fd84f91f412bd671a9d7.
Fixes #
```release-note
fix: allow back to build drivers for old libs versions
```

fix: add back PROBE_VERSION allowing drivers for old falcosecurity/libs versions to be built

---

pkg/driverbuilder/builder/amazonlinux.go

Based off of https://github.com/falcosecurity/driverkit/pull/138 by @dwindsor (which was closed in favor of this PR). This fixes #137 for newer amazonlinux2 kernels.
/kind bug
Please see reference in #138 
Additional details are without the change of LLVM version on 5.10 kernels we get the following error (debug logging enabled)
```
❯ ./_output/bin/driverkit docker --output-probe /tmp/probe.o --kernelversion=1 --kernelrelease="5.10.109-104.500.amzn2.x86_64" --driverversion=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4 --target=amazonlinux2 -l debug
DEBU running without a configuration file
DEBU running with options …
```

Fix: Ability to build 5.10 module and eBPF probe on AmazonLinux2

---

go.mod
go.sum
pkg/driverbuilder/builder/amazonlinux.go

* reversed symbolic link in amazonlinux2 builder script 
* updated a package version required for building on macOS as that seems to have broken
Signed-off-by: Austin Brogle <abrogle@snapchat.com>
/kind bug
/area pkg
Currently we had a lot of build errors with this new driverkit version in Prow build of test-infra https://prow.falco.org/view/s3/falco-prow-logs/logs/rebuild-all-drivers-amazonlinux2-periodic/1518943763240587264 which means that this repo is currently broken for amazonlinux2.
This was caused by a couple things:
1. A reversed symbolic link which caused an infinite loop of symbolic links when gcc pointed at gcc-8 by default and then we made gcc-8 point …

fix: reversed symbolic link in amazonlinux2 builder script

---

Makefile
cmd/docker.go
cmd/kubernetes.go
cmd/root.go
cmd/root_options.go
cmd/testdata/autohelp.txt
cmd/testdata/dockernoopts.txt
cmd/testdata/help-flag.txt
cmd/testdata/help.txt
cmd/testdata/invalid-proxyconfig.txt
cmd/testdata/non-existent-processor.txt
go.mod
go.sum
pkg/driverbuilder/builder/build.go
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/buildprocessor.go
pkg/driverbuilder/docker.go
pkg/driverbuilder/kubernetes.go
validate/isimagename.go
validate/validate.go

Signed-off-by: Luca Guerra <luca@guerra.sh>
This PR is co-authored with @Issif .
> /kind bug
> /kind design
/kind feature
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
The underlying problem that we're trying to solve is that some new kernel versions might require specific versions of base system libraries (mostly GNU libc) and/or specific compilers in order to build headers or modules compatible with that kernel. Think about GLIBC requirements for Ubuntu Impish or the latest Fedora.
A good step in doing …

new(driverkit): allow configurable builder images

---

README.md
build/builder.Dockerfile
cmd/testdata/completion-targets.txt
pkg/driverbuilder/builder/flatcar.go

**Example output**
```
./_output/bin/driverkit docker -l debug -t flatcar --kernelrelease 3255.0.0  --output-module=/tmp/falco.ko --driverversion master
DEBU running without a configuration file         
DEBU running with options                          arch=amd64 driverversion=master kernelrelease=3255.0.0 kernelversion=1 output-module=/tmp/falco.ko target=flatcar
INFO driver building, it will take a few seconds   processor=docker
DEBU doing a new docker build                     
DEBU kernel header url found                       url="https://alpha.release.flatcar-linux.net/amd64-usr/3255.0.0/flatcar_production_image_packages.txt"
DEBU kernel header url found                       url="https://alpha.release.flatcar-linux.net/amd64-usr/3255.0.0/flatcar_production_image_kernel_config.txt" …
```

Add builder for Flatcar

---

Makefile

/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
`docker buildx` in docker-container driver, does not create local tags for images. Therefore, we cannot just re-tag the "push/all" tagged images in the "push/latest" target.
We need to explicitly call `buildx` again. Note that the build is cached anyway.
Fixes #
**Does this PR introduce a …

fix(ci): fixed push latest images target.

---

Makefile

/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
CGO was wrongly enabled, and it caused cross compilation with goreleaser to arm64 to fail: 
```
gcc_arm64.S: Assembler messages:
gcc_arm64.S:28: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:32: Error: too many memory references for `mov'
...
```
Moreover, we now ship in our release page, really portable go binaries (that do not depend upon certaing …

fix(build): disable cgo.

---

pkg/driverbuilder/docker.go

/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Fixed a small potential issue while stopping the multiarch static container (ie: do not error out if the container is already stopped).
Fixes #
```release-note
NONE
```

fix(pkg): stopping a stopped container is not an error.

---

pkg/driverbuilder/builder/amazonlinux.go

> /kind bug
/kind cleanup
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Dropped requirement of 2 urls for amazonlinux (i could build various kernels without it; more testing needed!).
Fixes #
```release-note
cleanup(pkg): amazonlinux2 builder does now only need kernel-devel url.
```

new(pkg): drop requirements of `kernel` package for amazonlinux2 builder

---

pkg/driverbuilder/builder/ubuntu.go

Use gcc-10 when building ubuntu kernels >= 5.13.0

---

Makefile
pkg/driverbuilder/docker.go

/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Like #167 but for builder container. Avoids leaving with error even if kmod/probes were built but we fail to stop the container because it is already stopped.
Moreover, increased `integration_tests` target build timeout.
Fixes #
```release-note
NONE
```

fix: builder container stop, when already stopped

---

test/aarch64/configs/ubuntu.yaml
test/aarch64/configs/ubuntu_aws.yaml

/kind bug
/area tests
This fixes integration tests for arm64 after https://github.com/falcosecurity/libs/pull/416.  
Basically, 416 fixed drivers support for arm64; unfortunately, we had to bump the minimum required version for ebpf probe and kmod; see https://github.com/falcosecurity/libs#drivers-officially-supported-architectures.
Fixes #
```release-note
NONE
```

fix(test): fixed arm64 tests: eBPF probe requirement is now kernel >= 4.17

---

README.md
cmd/testdata/completion-targets.txt
pkg/driverbuilder/builder/amazonlinux.go

/kind feature
/area pkg
It adds amazonlinux2022 builder.
Moreover, refactored amazonlinux file making it easier to implement new builders.
Finally, updated README with the new al2022 example.
Tested: it is able to find the headers; then it fails to build the kmod because of glibc version issues (we really **need** multiple builders). eBPF probe builds fine.
Fixes #
```release-note
new(pkg): added amazonlinux 2022 builder.
```

new(pkg/driverbuilder): added amazonlinux2022 builder.

---

pkg/driverbuilder/builder/ubuntu.go

Signed-off-by: Logan Bond <lbond@secureworks.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
We are seeing build failures for ubuntu 5.11 and 5.19 kernel releases. It seems the GCC versions just need to be slightly adjusted.
Fixes #
```release-note
* Add gcc-11 support for 5.19
* Fix gcc-10 for 5.11
```

adjust ubuntu gcc versions

---

.gitignore
Makefile
cmd/root.go
cmd/root_options.go
cmd/testdata/autohelp.txt
cmd/testdata/completion-targets.txt
cmd/testdata/docker-target-redhat-validation-error-debug.txt
cmd/testdata/dockernoopts.txt
cmd/testdata/help-flag.txt
cmd/testdata/help.txt
cmd/testdata/invalid-proxyconfig.txt
cmd/testdata/non-existent-processor.txt
pkg/driverbuilder/builder/archlinux.go
pkg/driverbuilder/builder/build.go
pkg/driverbuilder/builder/templates/ubuntu.sh
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/ubuntu_test.go
pkg/kernelrelease/kernelrelease.go
test/aarch64/configs/ubuntu.yaml

> /kind bug
> /kind design
/kind feature
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Trying to simplify and expand Driverkit's Ubuntu support:
- Rather than having `ubuntu-generic` and `ubuntu-aws`, simplify to just `ubuntu`
- Expand support to more than just `generic` and `aws`, as described in: #144 
Fixes #144 
This work is also built in part on top of the work @amalone-scwx did in some internal testing - wanted to make sure I …

More Ubuntu Support

---

README.md
pkg/driverbuilder/builder/amazonlinux.go
pkg/driverbuilder/builder/archlinux.go
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/centos.go
pkg/driverbuilder/builder/debian.go
pkg/driverbuilder/builder/flatcar.go
pkg/driverbuilder/builder/photon.go
pkg/driverbuilder/builder/redhat.go
pkg/driverbuilder/builder/rocky.go
pkg/driverbuilder/builder/templates/debian.sh
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/vanilla.go
pkg/driverbuilder/docker.go
pkg/driverbuilder/kubernetes.go

/kind design
/area pkg
Refactor the single method Builder interface:
```Go
Script(c Config, kr kernelrelease.KernelRelease) (string, error)
```
to:
```Go
Name() string
TemplateScript() string
URLs(c Config, kr kernelrelease.KernelRelease) ([]string, error)
TemplateData(c Config, kr kernelrelease.KernelRelease, urls []string) interface{}
```
To reduce boiler plate of implementing the same Script method for each new builder.
This cuts down ~150locs from builders and makes writing a new builder even easier.
Moreover, updated README with new informations (archlinux builder too!).
Fixes #
**Does this …

chore: refactored builder interface to reduce boiler plate in each builder

---

pkg/driverbuilder/builder/centos.go

new(pkg): added centos9 stream support.

---

cmd/config_options.go
cmd/kubernetes.go
cmd/kubernetes_in_cluster.go
cmd/kubernetes_options.go
cmd/root.go
cmd/testdata/autohelp.txt
cmd/testdata/templates/commands.txt
docs/driverkit.md
docs/driverkit_docker.md
docs/driverkit_kubernetes-in-cluster.md
docs/driverkit_kubernetes.md
pkg/driverbuilder/builder/templates/amazonlinux.sh
pkg/driverbuilder/builder/templates/archlinux.sh
pkg/driverbuilder/builder/templates/centos.sh
pkg/driverbuilder/builder/templates/debian.sh
pkg/driverbuilder/builder/templates/flatcar.sh
pkg/driverbuilder/builder/templates/photonos.sh
pkg/driverbuilder/builder/templates/redhat.sh
pkg/driverbuilder/builder/templates/rocky.sh
pkg/driverbuilder/builder/templates/ubuntu.sh
pkg/driverbuilder/builder/templates/vanilla.sh
pkg/driverbuilder/kubernetes.go
pkg/driverbuilder/templates.go

/kind feature
/area cmd
/area pkg
* Adding a sub-command to use Kubernetes feature inside a kube pods with the appropriate service token/account.
* Adding configs/flags options to handle non root execution and pull secrets when using custom builder image.
* Fixing Kubenertes execution and probe module extraction. (Now extract module and probe properly, than delete the configmap and the pod)
~~To make non root execution works, I had to make a sub docker image builder with this owner change:~~
```
FROM falcosecurity/driverkit-builder
RUN chown -R nobody /usr/bin
```
~~I have to do this because driverkit's generated build …

feat(kebernetes-incluster): Adding kubernetes in cluster subcommand

---

pkg/driverbuilder/kubernetes.go
pkg/driverbuilder/templates.go

Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
/kind bug
/area pkg
Fix inconstancy in probe module extraction. This bug was due to  a too slow compilation, letting Driverkit trying to get the file while it was still empty. Diverse fixes on lock behavior.
None
```release-note
NONE
```

fix(kubernetes-probe): Fix inconstancy of probe file download + fix removing of the lock

---

Makefile
go.mod
go.sum

/kind bug
/area build
https://github.com/falcosecurity/driverkit/pull/186 introduced a subtle difference in the Makefile:
`BuilderBaseImage` makefile-set value was added a `_$(uname -m)` suffix.
This breaks cross builds because default value will try to use `docker.io/falcosecurity/driverkit-builder:$(commit)_x86_64` image for cross build (instead of the manifest-created one, ie: the one without arch suffix), resulting in wrong image being used for arm64 cross build.
Moreover, this PR also bumps some deps.
Fixes #
```release-note
NONE
```

fix: builderbaseimage default value in makefile

---

.circleci/config.yml

/kind cleanup
/area build
Disable for now integration tests to allow master ci to push new builder images.
I will enable them back once master CI is green.
Fixes #
```release-note
```

chore(ci): disable integration tests to allow master CI to push new builder images.

---

pkg/driverbuilder/docker.go
pkg/driverbuilder/kubernetes.go
pkg/driverbuilder/templates.go

/kind bug
/area pkg
To be able to be kept in sync with libs driver makefile, we download [the raw makefile](https://github.com/falcosecurity/libs/blob/master/driver/Makefile.in) for the required driverversion, and we load from it the required objects.
This is a bit ugly, because we will be going to download the entire repo at requested driverversion anyway, in each builder template.
Ideally, we'd want to move the repo download outside, load makefile objects, and share the volume with the builder image.
I will surely try to make this in a future PR.
Fixes #
**Does this PR introduce a user-facing …

fix(pkg/driverbuilder): dynamically load driver makefile objects by downloading Makefile.in from libs github

---

Example_configs.md
cmd/root_options.go
pkg/driverbuilder/builder/amazonlinux.go
pkg/driverbuilder/builder/archlinux.go
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/centos.go
pkg/driverbuilder/builder/debian.go
pkg/driverbuilder/builder/flatcar.go
pkg/driverbuilder/builder/photon.go
pkg/driverbuilder/builder/redhat.go
pkg/driverbuilder/builder/rocky.go
pkg/driverbuilder/builder/templates/flatcar.sh
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/ubuntu_test.go
pkg/driverbuilder/builder/vanilla.go
validate/validate.go

/kind bug
/area pkg
Fix a crash in the flatcar builder; moreover, make it actually work.
Basically it is now the same as vanilla/minikube builders, with some small differences. It will now require `kernelconfigdata` option. That is much more smart than fetching the kernelconfigdata URL only to download it in the template script, considering that we already had a `kernelconfigdata` option in driverkit.
Moreover, moved all builder structs receivers to pointers, so that we can actually update any struct members in receiver methods.
Finally, actually require `kernelconfigdata` param for minikube and flatcar too.
This goes together with …

fix(pkg,cmd,validate): fixed flatcar builder

---

cmd/root.go
cmd/root_options.go
cmd/testdata/templates/flags.txt
go.mod
go.sum
pkg/driverbuilder/builder/build.go
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/builders_test.go
pkg/driverbuilder/builder/debian.go
pkg/driverbuilder/builder/flatcar.go
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/ubuntu_test.go
pkg/driverbuilder/builder/vanilla.go
pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go
validate/isimagename.go
validate/semver.go
validate/validate.go

/kind cleanup
/area cmd
/area pkg
/area tests
This PR enforces the use of a semver library to manage:
* gcc versions
* kernel versions
Moreover, it updates and fixes an ubuntu test (as always, the ubuntu header for the old test-case was no more there; just updated the test version)
Fixes #
```release-note
NONE
```

chore: use semver package for gcc versions and kernel versions.

---

.circleci/config.yml

/kind bug
/area build
`circleci/golang` images are not supported anymore; there is no 1.18 tag for them.
Switch to new cimg/go images.
Fixes #
```release-note
NONE
```

fix: use cimg/go image instead of the old circleci/golang one for release job

---

pkg/driverbuilder/templates.go

Signed-off-by: Logan Bond <lbond@secureworks.com>
/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
It appears that one some Falco libs versions modules fail to build with an error "obj list not found". When tracking down the error, it comes from this function:
```
func LoadMakefileObjList(c builder.Config) (string, error) {
makefileUrl := fmt.Sprintf("https://raw.githubusercontent.com/%s/%s/%s/driver/Makefile.in", c.RepoOrg, c.RepoName, c.DriverVersion) …
```

add check for @PROBE

---

pkg/driverbuilder/builder/templates/ubuntu.sh
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/ubuntu_test.go

/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Adjusting the `headersPattern` for Ubuntu. See #223 
Splitting the `flavor` on `-` should return just the first part of the flavor, which will still work for the `headersPattern`. If the `flavor` does not contain `-`, then it should just return the original `flavor` like normal.
Fixes #223  …

Adjust `headersPattern` Detection for Ubuntu

---

pkg/driverbuilder/builder/ubuntu.go

Forgot a `*` in the Ubuntu `headersPattern`

---

cmd/root_options.go
pkg/driverbuilder/builder/ubuntu_test.go
pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

/kind feature
/area cmd
/area pkg
This updates the tool to figure out if the kmod and the eBPF probes are not supported on a given kernel release, so that we can avoid trying to build a config proven to be unfeasible. The goal is to save CPU and building time in the CI.
```release-note
update: avoid building unfeasible kmods and probes
```

update: avoid building unfeasible kmods and probes

---

pkg/driverbuilder/builder/fedora.go
pkg/driverbuilder/builder/templates/fedora.sh

> /kind bug
> /kind design
/kind feature
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Just adding initial Fedora support 🙂 
Fixes # N/A
I tested these chages with kernel-crawler output:
```shell
╰─❯ kernel-crawler crawl --distro Fedora --out_fmt driverkit | jq -r '.Fedora[] | .kernelrelease'
Checking repositories  [####################################]  100%                                                       
Listing packages …
```

Add Initial Fedora Support

---

pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

Signed-off-by: Logan Bond <lbond@secureworks.com>
/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
I found some strange Debian kernels with kernel crawler in my testing... However, driverkit fails to build all of them:
```
- '4.9.65-2+grsecunoff1~bpo9+1-amd6'
- '4.19.118-2+deb10u1~bpo9+1-amd64'
- '5.10.127-2~bpo10+1-amd64'
- '5.19.11-1~bpo11+1-amd64'
- '5.10.136-1~deb10u3-amd64'
- '4.9.189-3+deb9u2~deb8u1-amd64'
- '4.19.232-1~deb9u1-amd64' 
```
Tracing it back …

Draft: Adjust the `kernelVersionPattern` to match some weird Debian kernels

---

pkg/driverbuilder/builder/fedora.go

/kind feature
/area pkg
Previously when attempting to build the driver for `5.19.16-301.fc37.x86_64_1` we could not. This is because the fedora core 37 isn't in final release and is still in the development section of the repo so it couldn't actually find and download the kernel headers. By adding this, we are now able to download the kernel headers and ultimately build fc37 probes.

feat: add development fedora repos to enable building of driver for fc37 which isn't in final release yet

---

Makefile
cmd/root.go
cmd/root_options.go
cmd/testdata/templates/flags.txt
docs/driverkit.md
docs/driverkit_docker.md
docs/driverkit_kubernetes-in-cluster.md
docs/driverkit_kubernetes.md
pkg/driverbuilder/builder/build.go
pkg/driverbuilder/builder/builders.go

config flag for custom base image to override the compile-time defined BaseImage
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
/kind feature
/area cmd
/area pkg
/area docs
In order to use proxy images and to avoid defining a single image to the command line and still benefit the auto-choose based on GCC version need by the kernel
None
I included a mini fix of the Makefile, the `make docs` was erasing builder and builder_image doc.
And it seems that a pretty big part of the docs was missing.
```release-note
new option: …
```

feat(builder-image): config flag for custom base image

---

pkg/kernelrelease/kernelrelease.go

/kind bug
/area pkg
Some arch kernels are just named `6.1.arch1-1`. Therefore, allow empty patch level while parsing kernelrelease string.
Fixes #
```release-note
fix(pkg/kernelrelease): allow empty patch level string while parsing kernelrelease.
```

fix(pkg/kernelrelease): allow empty patch for kernelrelease strings.

---

pkg/driverbuilder/builder/rocky.go

```
Break out the vault releases from the mainstream releases, and append them all to the url list
```
/kind bug
/area pkg
Rocky Linux uses two different areas for their packages based on whether its a current release version or a previous.  The previous ones are put at a vault url, so the update was required to add a separate list of vault releases to support when looking for the urls to find the kernel-devel package.
Fixes #245 
```release-note
NONE
```

fix(pkg/driverbuilder): rocky release urls

---

pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

This PR will further improve the way kernel release names are parsed.
This is the case of distributions like Debian which applies a semantic for which a separator can be the the plus character ('+').
For example, with this change, a release named '4.19+105+deb10u4~bpo9+1' will be matched and the change will allow parsing by capturing the resulting regular expression named capturing groups.
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
/kind bug
/area pkg
Fixes #247 
NA
```release-note
NONE
```

fix(pkg/kernelrelease): allow plus char as sublevel and extra separator

---

pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

/kind cleanup
/area pkg
See https://github.com/falcosecurity/libs/pull/843
Fixes #
```release-note
NONE
```

fix(pkg): minimum kver to build kmod for arm64 is 3.16.

---

pkg/driverbuilder/builder/amazonlinux.go

Signed-off-by: Austin Brogle <abrogle@snapchat.com>
/kind feature
/area pkg
Previously when running:
```bash
driverkit docker --builderimage docker.io/falcosecurity/driverkit-builder_bookworm:v0.11.1 --output-probe ./falco_amazonlinux2_5.15.43-20.123.amzn2.aarch64_1.o --architecture=arm64 --kernelversion=1 --kernelrelease=5.15.43-20.123.amzn2.aarch64 --driverversion=3.0.1+driver --target amazonlinux2 -l debug --timeout 480
```
I would get:
```
DEBU running without a configuration file
DEBU running with options                          arch=arm64 driverversion=3.0.1+driver kernelrelease=5.15.43-20.123.amzn2.aarch64 kernelversion=1 …
```

feat: support amazonlinux2 5.15.x kernel

---

Makefile

/kind cleanup
/area tests
#244 added a `builderrepo` option poiting at my dockerhub repo to tests, to allow them to pass.
Clean it up now that we have falcosecurity images.
Fixes #
```release-note
NONE
```

cleanup: removed `builderrepo` option pointing to my dockerhub.

---

docker/builders/builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0.Dockerfile
validate/isimagename.go

/kind bug
> /kind design
> /area build
/area cmd
> /area pkg
> /area docs
> /area tests
We have some builder images that use uppercase characters in the tag name. For example:
```
example.com/oraclelinux7:AG-8537-oracle-support
```
These fail the validation on `--builderimage` due to the uppercase characters. The alphabet used for validation is locked to lowercase.
Fixes # N/A
Also added `mawk` to the builderimage, which is required by …

Fixing Image Name Validation for Builder Image Flag

---

pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/builders_test.go

/kind bug
> /kind design
> /area build
> /area cmd
/area pkg
> /area docs
> /area tests
Simply adjusting the GCC selector to use GCC 12 for kernels 5.15+ rather than just 5.18+
We noticed some issues in our infrastructure where GCC 11 was selected for kernels 5.15.x for Oracle, and none of them build. Adding the `--gccversion 12.0.0` flag fixes the builds. 
To then test that changing 5.15+ to GCC 12 doesn't break anything else, I deleted all 5.15.x kernels in our dev environment to rebuild them with the …

Adjust GCC 12 Selector to Kernels 5.15+

---

pkg/driverbuilder/builder/templates/vanilla.sh
pkg/driverbuilder/builder/vanilla.go
pkg/kernelrelease/kernelrelease_test.go

/kind feature
/area pkg
This PR adds support for release candidates for vanilla target.
Is going to be used to improve libs [`latest-kernel`](https://github.com/falcosecurity/libs/blob/master/.github/workflows/latest-kernel.yml) CI to test the build against latest mainline kernel available (RCs too!), so that we get notified asap when a kernel breaks our drivers build! :) 
See: https://github.com/falcosecurity/libs/pull/1090
Fixes #
```release-note
new(pkg): support RC releases for vanilla target
```

new(pkg): support RC releases for vanilla target.

---

Example_configs.md

/area docs
Only adds additional documentation which should make it easier to get started.
Added documentation for RHEL9 builder images where the underlying host is different. This is not covered in the documentation yet. Also, I added a line in the Dockerfile for RHEL9 images which fixes a bug that driverkit couldn't find the gcc-11 binary in rhel9 because a symlink from the redhat version of gcc-11 was missing.
No
```release-note
Added additional documentation for RHEL9 builder images
```

Fb update rhel9 example

---

pkg/driverbuilder/builder/templates/vanilla.sh
pkg/driverbuilder/builder/vanilla.go

/kind bug
/area pkg
Moreover, properly enforce KBUILD_MODPOST_WARN in vanilla template.
It was previously enabled by default; but this commit: https://github.com/torvalds/linux/commit/5573b4daa26a0cf15aa0fecd7f1be16e0b6157bc merged in linux 6.3, changed the behavior.
Thus we now need to enforce it.
Fixes #
```release-note
NONE
```

fix(pkg): fixed mainline kernel URLs.

---

cmd/root.go
cmd/root_options.go
cmd/testdata/autohelp.txt
cmd/testdata/help-flag.txt
cmd/testdata/invalid-proxyconfig.txt
cmd/testdata/non-existent-processor.txt
cmd/testdata/templates/flags.txt
docs/driverkit.md
docs/driverkit_docker.md
docs/driverkit_images.md
docs/driverkit_kubernetes-in-cluster.md
docs/driverkit_kubernetes.md
pkg/driverbuilder/builder/build.go
pkg/driverbuilder/builder/image.go
pkg/driverbuilder/builder/image_test.go

> /kind bug
> /kind design
/kind feature
> /area build
/area cmd
> /area pkg
> /area docs
/area tests
This PR supports authentication when listing tags from private repositories. 
Please note that, once the `builder image` has been found the docker daemon needs to be authenticated if pulling from a private repository. 
Fixes #
The PR is based on #280, hence that's way there are two additional commits. Before merging a rebase is needed.
**Does this PR …

feat(imagelister): support private repositories to list builder images

---

pkg/driverbuilder/builder/templates/centos.sh

/kind bug
> /kind design
/area build
> /area cmd
> /area pkg
> /area docs
> /area tests
We've noticed some failures with recent CentOS 5.14.x kernels:
```
[
"scwx_centos_5.14.0-331.el9.x86_64_1.ko",
"scwx_centos_5.14.0-333.el9.x86_64_1.ko",
"scwx_centos_5.14.0-330.el9.x86_64_1.ko",
"scwx_centos_5.14.0-325.el9.x86_64_1.ko",
"scwx_centos_5.14.0-319.el9.x86_64_1.ko"
],
```
They fail with this error: 
```
DEBU *make -C /tmp/kernel M=/tmp/driver modules
DEBU *make[1]: Entering directory '/tmp/kernel'
DEBU   CC …
```

Add KCFLAG for CentOS to Fix Builds of Some Modules

---

go.sum
pkg/driverbuilder/builder/aliyunlinux.go
pkg/driverbuilder/builder/almalinux.go
pkg/driverbuilder/builder/amazonlinux.go
pkg/driverbuilder/builder/archlinux.go
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/centos.go
pkg/driverbuilder/builder/debian.go
pkg/driverbuilder/builder/fedora.go
pkg/driverbuilder/builder/flatcar.go
pkg/driverbuilder/builder/opensuse.go
pkg/driverbuilder/builder/oracle.go
pkg/driverbuilder/builder/photon.go
pkg/driverbuilder/builder/redhat.go
pkg/driverbuilder/builder/rocky.go
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/vanilla.go

/kind cleanup
/area pkg
Reduce `URLs` builder interface method signature avoiding the unused `config` parameter.
It was only used by `ubuntu` builder to fetch build kernelversion; we can use viper for that.
This makes much more practical to use driverkit builder as library in other go projects, because you don't need to instantiate a full driverkit config to fetch URLs; for example:
```Go
var kernelheaders []string
builder, err := builder.Factory(builder.Type(myTarget))
if err != nil {
logger.Warn(err.Error())
} else {
kr := kernelrelease.FromString(myKernelRelease)
kernelheaders, err = builder.URLs(kr)
if err != nil {
logger.Warn(err.Error())
}
logger.Info("Got …
```

cleanup(pkg): cleaned up URLs builder interface method removing config parameter

---

cmd/docker.go
cmd/images.go
cmd/kubernetes.go
cmd/kubernetes_in_cluster.go
cmd/root_options.go

/kind cleanup
/area cmd
Expose the `ToBuild` method; this allows external applications to run driverkit as library, eg:
```
ro := cmd.RootOptions{...values...}
return driverbuilder.NewDockerBuildProcessor(1000, "").Start(ro.ToBuild())
```
At the moment, clients would have to completely reimplement the `ToBuild` method themselves.
Fixes #
```release-note
NONE
```

chore(cmd): expose ToBuild method.

---

pkg/driverbuilder/builder/build.go
pkg/driverbuilder/builder/ubuntu.go
pkg/driverbuilder/builder/ubuntu_test.go
pkg/kernelrelease/kernelrelease.go

/kind cleanup
/area pkg
Since it is only used by ubuntu, avoid directly calling `viper.GetString()`.
Fixes #
```release-note
NONE
```

cleanup(pkg): store kernelversion inside the kernelrelease type.

---

pkg/driverbuilder/docker.go

/kind bug
/area pkg
When docker container attach is called on a non-tty terminal, stray characters will appear on screen because the docker SDK uses a custom multiplexing protocol allowing STDOUT and STDERR string to be sent to a single stream.
So, we now check if we are running multiplexed and adapt consequently.
Fixes #
```release-note
NONE
```

fix(pkg/driverbuilder): fixed docker container output when multiplexed.

---

cmd/config_options.go
cmd/local.go
cmd/root.go
cmd/testdata/autohelp.txt
cmd/testdata/templates/commands.txt
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/local.go
pkg/driverbuilder/builder/templates/local.sh
pkg/driverbuilder/local.go

/kind feature
/area cmd
/area pkg
This PR introduces a new `local` build processor that will just build chosen driver version against local kernel sources using local gcc/clang.
Therefore, to work, it needs kernel-headers installed (eg: `/lib/modules/6.6.1-arch1-1/build`) and clang/gcc on the machine.
It does not use docker, of course.
Moreover, it supports building kmod through `dkms`, and supports directly using a provided preconfigured `src-dir`.
The bigger aim is to completely implement driver building logic that is today part of [`falco-driver-loader script`](https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader); this would allow us …

new(cmd,pkg): added new `local` build processor to build drivers using local kernel sources/gcc/clang

---

docker/builders/builder-any-x86_64_gcc10.0.0_gcc9.0.0.Dockerfile
docker/builders/builder-any-x86_64_gcc12.0.0_gcc11.0.0.Dockerfile
docker/builders/builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0.Dockerfile
docker/builders/builder-centos-x86_64_gcc4.8.5.Dockerfile

/kind feature
/area build
Split from #302 ; add cmake and git packages to builder images.
Fixes #
```release-note
new(docker): add cmake and git to builder images
```

new(docker): add `cmake` and `git` packages to builders images.

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/reusable_build_test_driverkit.yml
docker/builders/builder-any-aarch64_gcc13.0.0.Dockerfile
docker/builders/builder-any-x86_64_gcc13.0.0.Dockerfile
pkg/driverbuilder/builder/builders.go

/kind feature
/area build
/area pkg
This PR introduces a new fedora based `any` builder to be able to build recent kernels (6.6+)  that require glibc 2.38.
Fixes #303 
```release-note
new: added a new glibc 2.38 gcc 13 based builder image.
```

new: glibc 2.38 builder

---

pkg/driverbuilder/builder/templates/debian.sh
pkg/driverbuilder/builder/templates/opensuse.sh
pkg/driverbuilder/builder/templates/sles.sh
pkg/driverbuilder/builder/templates/ubuntu.sh

/kind cleanup
/area pkg
This PR makes build templates less verbose by dropping a `tar` `-v` flag and some debug `ls`.
Fixes #
```release-note
NONE
```

cleanup: no verbose tar and avoid ls

---

pkg/driverbuilder/kubernetes.go

/kind feature
/area pkg
This implements support for arm64 build for kubernetes executor.
Fixes #
```release-note
NONE
```

new(pkg/driverbuilder): added a node selector for kubernetes executor's pod on `kubernetes.io/arch` label

---

pkg/driverbuilder/builder/debian.go

/kind bug
/area pkg
This PR fixes support to fetch kernel headers for debian `rpi` and `rt` flavors, where the `common` package has the `-$flavor` suffix.
Fixes #
Example:
```
./_output/bin/driverkit docker --target debian --kernelrelease 4.19.0-26-rt-amd64 --kernelversion 1 --output-probe /tmp/mod.o --loglevel debug --builderimage auto:master
level=DEBUG msg="running without a configuration file"
level=DEBUG msg="running with options" output-module="" output-probe=/tmp/mod.o driverversion=master kernelrelease=4.19.0-26-rt-amd64 kernelversion=1 target=debian arch=amd64 kernelurls=[] …
```

fix(pkg/driverbuilder): fixed debian `rpi` and `rt` flavors kernel urls fetching

---

pkg/driverbuilder/builder/templates/alinux_kernel.sh
pkg/driverbuilder/builder/templates/almalinux_kernel.sh
pkg/driverbuilder/builder/templates/amazonlinux_kernel.sh
pkg/driverbuilder/builder/templates/archlinux_kernel.sh
pkg/driverbuilder/builder/templates/centos_kernel.sh
pkg/driverbuilder/builder/templates/debian_kernel.sh
pkg/driverbuilder/builder/templates/fedora_kernel.sh
pkg/driverbuilder/builder/templates/flatcar_kernel.sh
pkg/driverbuilder/builder/templates/opensuse_kernel.sh
pkg/driverbuilder/builder/templates/oracle_kernel.sh
pkg/driverbuilder/builder/templates/photonos_kernel.sh
pkg/driverbuilder/builder/templates/redhat_kernel.sh
pkg/driverbuilder/builder/templates/rocky_kernel.sh
pkg/driverbuilder/builder/templates/sles_kernel.sh
pkg/driverbuilder/builder/templates/ubuntu_kernel.sh
pkg/driverbuilder/builder/templates/vanilla_kernel.sh
pkg/driverbuilder/docker.go
pkg/driverbuilder/kubernetes.go
pkg/driverbuilder/local.go

/kind bug
/area pkg
Fix on top of #324 (this comment was highly specific: https://github.com/falcosecurity/driverkit/pull/324#discussion_r1524730462 :D)
It also fixes vanilla kernel builds; see libs CI that is badly failing since we released driverkit v0.18.0: https://github.com/falcosecurity/libs/actions/workflows/latest-kernel.yml
Fixes #
```release-note
NONE
```

fix(pkg/driverbuilder): properly export KERNELDIR in kernel-download scripts

---

.github/workflows/ci.yml
.github/workflows/master.yml
.github/workflows/release.yml
.github/workflows/reusable_build_push_images.yml
docker/builders/builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0.Dockerfile

/kind bug
/area build
Debian-buster backports repo is no more present upstream: https://github.com/falcosecurity/driverkit/actions/runs/8749618529/job/24013163670
Also, enable build-dev CI to test images build if `docker` folder was updated.
Fixes #
```release-note
NONE
```

chore(docker): fix master CI by using debian:buster with no backports repo for gcc8 builder

---

pkg/driverbuilder/builder/templates/local.sh
pkg/driverbuilder/local.go

/kind bug
/area pkg
Fix on top of #342: remove `-u` flag from local template `set` bash command, since we reference unexisting env var in the template, and it would lead to failure: 
> -u
>
>    Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’, or array variables subscripted with ‘@’ or ‘*’, as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit.
Fixes #
```release-note
NONE
```

fix(pkg/driverbuilder): fixed local builder template.

---

docs/builder.md

The 'Target name' subsection is old. `BuilderByTarget` isn't used anymore; it's now `byTarget` in `target.go`. Add a hyperlink for clarity and accessibility.
/kind cleanup
/area pkg
/area docs
The commit by @FedeDP seems to have caused this https://github.com/falcosecurity/driverkit/commit/56573f405914c2bb63b77a2bf8f0f3e64c8afde3, but it appears that the documentation hasn't been updated to match the current logic of the builders.
No
No

docs/builder.md: remove BuilderByTarget references

---

docker/builders/builder-amazonlinux2-x86_64_gcc10.0.0.Dockerfile
pkg/driverbuilder/builder/amazonlinux.go

/kind feature
/area build
/area pkg
This fixes driver build issues on al2 5.10 kernels triggered by the new [kmod configure system](https://github.com/falcosecurity/libs/pull/1452).
Refs: https://github.com/falcosecurity/falco/issues/3244
Fixes #
Already tested by pushing on my fededp dockerhub repo:
```
2024-06-12 09:45:42 DEBUG [configure-kmod] Setting HAS_ACCESS_OK_2 flag 
2024-06-12 09:45:45 DEBUG Built target driver 
2024-06-12 09:45:45 DEBUG + strip -g /tmp/driver/build/driver/falco.ko 
2024-06-12 09:45:45 DEBUG + modinfo …
```

new(pkg,docker): added an amazonlinux2 gcc10 builder.

---

.github/workflows/ci.yml

> /kind bug
> /kind design
> /area build
> /area cmd
> /area pkg
> /area docs
> /area tests
Fixes #
```release-note
```

fix(ci): fix paths filters

---

docker/builders/builder-centos-x86_64_gcc4.8.5.Dockerfile

/kind bug
/area build
Since centos7 is now EoL, we need to swap the centos7 builder repo to the `vault.centos.org` archive.
Also, fixes master CI.
Fixes #
```release-note
NONE
```

fix(docker): fixed centos7 builder because of EoL.

---

pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go

/kind bug
/area pkg
COS kernels have `5.10.6+` form, that was previously not allowed by our regex. Fix it.
Refs: https://github.com/falcosecurity/falco/issues/3278
Fixes #
```release-note
fix(pkg/kernelrelease): fixed kernelrelease regex for weird COS kernels.
```

fix(pkg/kernelrelease): fixed kernelrelease regex for weird COS kernels.

---

docker/builders/builder-any-x86_64_gcc8.0.0_gcc6.0.0_gcc5.0.0_gcc4.9.0_gcc4.8.0.Dockerfile

/kind feature
/area build
As per title
Fixes #
```release-note
NONE
```

update(build): update cmake in debian buster image to 3.22

---

docker/builders/builder-arch-x86_64_gcc14.2.1.Dockerfile
pkg/driverbuilder/builder/archlinux.go
pkg/driverbuilder/builder/builders.go

/kind bug
/area pkg
The PR fixes an issue with archlinux URLs string builder; moreover, to fix recent archlinux kernels build, it adds a new builder image based on archlinux with gcc 14.2.1.
Fixes #
```release-note
fix: archlinux support
```

fix: archlinux support

---

docker/builders/builder-any-aarch64_gcc14.0.0.Dockerfile
docker/builders/builder-any-x86_64_gcc14.0.0.Dockerfile
docker/builders/builder-arch-x86_64_gcc14.2.1.Dockerfile
pkg/driverbuilder/builder/builders.go

/kind bug
/area pkg
In https://github.com/falcosecurity/driverkit/pull/372, we added an archlinux specific gcc 14 image to fix drivers build against linux >= 6.10.
It turned out, that change is not archlinux specific but is an upstream change: https://lore.kernel.org/lkml/ZdXVk41lSMLx_Fmg@FVFF77S0Q05N/
This is why our drivers pipeline is failing for ubuntu 6.11 (and probably many more recent drivers).
Thus, i added an `any`-distro gcc 14 image; also, dropped archlinux-specific gcc14.0.0 image.
Fixes #
```release-note
new(docker): add an …
```

new(docker): add a `any` distro gcc 14.0.0 image.

---

go.mod
go.sum
pkg/driverbuilder/builder/amazonlinux.go
pkg/driverbuilder/builder/builders.go
pkg/driverbuilder/builder/builders_test.go
pkg/driverbuilder/builder/centos.go
pkg/driverbuilder/builder/flatcar.go
pkg/driverbuilder/builder/image.go
pkg/driverbuilder/builder/image_test.go
pkg/driverbuilder/builder/minikube.go
pkg/driverbuilder/builder/ubuntu_test.go
pkg/kernelrelease/kernelrelease.go
pkg/kernelrelease/kernelrelease_test.go
validate/semver.go

/kind cleanup
/area pkg
The semver package moved to the versioned import path some time back. Move to /v4 to sync with falcoctl and avoid pulling in two copies of the module.
```release-note
NONE
```

chore(deps): migrate blang/semver to v4
